{% set name = "pygments-style-solarized" %}
{% set version = "100.10.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygments-style-solarized-{{ version }}.tar.gz
  sha256: bd51d216368549de3bf45c63f0ef2aff3efdea5accce0ea2b4a434e7fbdd7414

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry >=1,<2
  run:
    - pygments >=1.5
    - python >=3.6,<4.0

test:
  imports:
    - pygments_style_solarized
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/shkumagai/pygments-style-solarized
  summary: Pygments version of the Solarized theme.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
